parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'mysql://root:@127.0.0.1:3306/s'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                DATE: DoctrineExtensions\Query\Mysql\Date
                MONTH: DoctrineExtensions\Query\Mysql\Month
                MONTHNAME: DoctrineExtensions\Query\Mysql\MonthName
                YEAR: DoctrineExtensions\Query\Mysql\Year
                DAY: DoctrineExtensions\Query\Mysql\Day
                IF: DoctrineExtensions\Query\Mysql\IfElse
                TIMESTAMPDIFF: DoctrineExtensions\Query\Mysql\TimestampDiff
                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
