easy_admin:
    site_name: '<strong>PANEL DE ADMINISTRACIÓN Benditotrabajo.com</strong>'
    design:
      brand_color: '#3B5998'
      assets:
        css:
          - '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">'
        js:
          - '<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>'
          - '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>'
          - '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>'
    entities:
      Usuarios:
        class: App\Entity\User
        list:
          fields:
#            - { property: 'image', type: 'image', base_path: '%app.path.user_images%' }
            - name
            - username
            - email
            - enabled
            - lastLogin
            - roles
        form:
          fields:
#            - { property: 'imageFile', type: 'file', base_path: '%app.path.user_images%' }
            - name
            - username
            - email
            - enabled
            - lastLogin
            - { property: 'plainPassword', type: 'text', type_options: { required: false } }
            - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN','ROLE_SUPER_ADMIN':'ROLE_SUPER_ADMIN' } } }

      Categorias:
        class: App\Entity\Category
        form:
          fields:
            - name
            - description
            - ico
        list:
          fields:
            - name
            - description
            - ico
      Empleos:
        class: App\Entity\Job
        form:
          fields:
            - title
#            - { property: 'imageFile', type: 'file', base_path: '%app.path.company_images%' }
        list:
          fields:
            - title
            - category
            - user
            - company_name
            - image
      Titulos:
        class: App\Entity\Title
        form:
          fields:
          - name
          - description
        list:
          fields:
          - name
          - description
      Profesiones:
        class: App\Entity\Profession
        form:
          fields:
          - name
          - description
        list:
          fields:
          - name
          - description
      Politica_de_privacidad:
        class: App\Entity\Policy
        form:
          fields:
            - welcome_message
            - privacity
            - information
            - security
            - terms_header
            - terms
            - conditions_header
            - conditions
            - updated
        list:
          fields:
            - welcome_message
            - privacity
            - information
            - security
            - terms_header
            - terms
            - conditions_header
            - conditions
            - updated
      Servicios:
        class: App\Entity\Service
        form:
          fields:
            - name
        list:
          fields:
            - name
