fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address: "uafonseca@uci.cu"
        sender_name: "Sender Name"

