fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address: "pauqqhnarhjujepf"
        sender_name: "Bendito Trabajo"

