sonata_seo:
    encoding:         UTF-8
    page:
        title:           'Bendito Trabajo Ecuador'
        title_prefix:  'Bendito Trabajo |'
        # title_suffix:  '| Suffix'
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             empleo trabajo oferta servicios ecuador laboral personal currículun vitae hoja de vida
                description:          Estamos enfocados en el proceso de socialización de las ofertas de empleo en Ecuador
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Bendito Trabajo Ecuador
                'og:description':     Estamos enfocados en el proceso de socialización de las ofertas de empleo en Ecuador

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
