twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'theme_templates/bootstrap_3_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'form/custom_form_types.html.twig'
